FROM python:3.8

ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /app/requirements.txt

RUN /usr/local/bin/python -m pip install --upgrade pip \
    && pip install --no-cache-dir -r /app/requirements.txt \
    && rm -rf /app/requirements.txt
